name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - istefan/change-to-sphinx
  pull_request:
    types: [opened,reopened,edited,synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme ghp-import

      - name: Build Sphinx documentation
        run: |
          sphinx-build -M html ./source ./build

      # - name: Perform link check
      #   run: |
      #     sphinx-build -M linkcheck ./source ./build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: github-pages
          path: |
            build/html/*

      - name: Generate a token for the UASAL builder app
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/istefan/change-to-sphinx'
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          publish_dir: build/html